services:
  mm-backend:
    build:
      context: ./packages/mm-backend
      dockerfile: Dockerfile
    container_name: mm-backend
    working_dir: /usr/src/app/packages/mm-backend
    command: ["pnpm", "start"]
    ports:
      - "3000:3000"
    environment:
      TRADING_STRATEGY_EXECUTION_URL: ${TRADING_STRATEGY_EXECUTION_URL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      MIXIN_APP_ID: ${MIXIN_APP_ID}
      MIXIN_SESSION_ID: ${MIXIN_SESSION_ID}
      MIXIN_SERVER_PUBLIC_KEY: ${MIXIN_SERVER_PUBLIC_KEY}
      MIXIN_SESSION_PRIVATE_KEY: ${MIXIN_SESSION_PRIVATE_KEY}
      MIXIN_SPEND_PRIVATE_KEY: ${MIXIN_SPEND_PRIVATE_KEY}
      MIXIN_OAUTH_SECRET: ${MIXIN_OAUTH_SECRET}
      MIXIN_OAUTH_SCOPE: ${MIXIN_OAUTH_SCOPE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_LOGGING_LEVEL: ${DATABASE_LOGGING_LEVEL}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE}
      DATABASE_AUTO_RUN_MIGRATIONS: ${DATABASE_AUTO_RUN_MIGRATIONS}
      DATABASE_SSL: ${DATABASE_SSL}
      REDIS_URL: ${REDIS_URL}

  tse-backend:
    build:
      context: ./packages/tse-backend
      dockerfile: Dockerfile
    container_name: tse-backend
    working_dir: /usr/src/app/packages/tse-backend
    command: ["pnpm", "start"]
    ports:
      - "3001:3001"
    environment:
      SANDBOX: ${SANDBOX}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_LOGGING_LEVEL: ${DATABASE_LOGGING_LEVEL}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE}
      DATABASE_AUTO_RUN_MIGRATIONS: ${DATABASE_AUTO_RUN_MIGRATIONS}
      DATABASE_SSL: ${DATABASE_SSL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - db
      - redis
  db:
    image: postgres
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data