version: '3.8'

services:
  mm-backend:
    build:
      context: ./packages/mm-backend
      dockerfile: Dockerfile
    container_name: mm-backend
    working_dir: /usr/src/app/packages/mm-backend
    command: ["pnpm", "start"]
    ports:
      - '${MM_BE_PORT}:${MM_BE_PORT}'
    environment:
      CORS_ORIGIN: ${CORS_ORIGIN}
      MM_BE_PORT: ${MM_BE_PORT}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_LOGGING_LEVEL: ${DATABASE_LOGGING_LEVEL}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE}
      DATABASE_AUTO_RUN_MIGRATIONS: ${DATABASE_AUTO_RUN_MIGRATIONS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      TRADING_STRATEGY_EXECUTION_API: ${TRADING_STRATEGY_EXECUTION_API}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      MIXIN_APP_ID: ${MIXIN_APP_ID}
      MIXIN_SESSION_ID: ${MIXIN_SESSION_ID}
      MIXIN_SERVER_PUBLIC_KEY: ${MIXIN_SERVER_PUBLIC_KEY}
      MIXIN_SESSION_PRIVATE_KEY: ${MIXIN_SESSION_PRIVATE_KEY}
      MIXIN_SPEND_PRIVATE_KEY: ${MIXIN_SPEND_PRIVATE_KEY}
      MIXIN_OAUTH_SECRET: ${MIXIN_OAUTH_SECRET}

  tse-backend:
    build:
      context: ./packages/tse-backend
      dockerfile: Dockerfile
    container_name: tse-backend
    working_dir: /usr/src/app/packages/tse-backend
    command: ["pnpm", "start"]
    ports:
      - '${TSE_BE_PORT}:${TSE_BE_PORT}'
    environment:
      CORS_ORIGIN: ${CORS_ORIGIN}
      TSE_BE_PORT: ${TSE_BE_PORT}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_LOGGING_LEVEL: ${DATABASE_LOGGING_LEVEL}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE}
      DATABASE_AUTO_RUN_MIGRATIONS: ${DATABASE_AUTO_RUN_MIGRATIONS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      WS_PORT: ${WS_PORT}
      WS_NAMESPACE: ${WS_NAMESPACE}
      WS_CORS_ORIGIN: ${WS_CORS_ORIGIN}
      CRON_EXPRESSION: ${CRON_EXPRESSION}
      EXCHANGE_BINANCE_API: ${EXCHANGE_BINANCE_API}
      EXCHANGE_BINANCE_SECRET: ${EXCHANGE_BINANCE_SECRET}
      EXCHANGE_GATE_API: ${EXCHANGE_GATE_API}
      EXCHANGE_GATE_SECRET: ${EXCHANGE_GATE_SECRET}
      EXCHANGE_BITFINEX_API: ${EXCHANGE_BITFINEX_API}
      EXCHANGE_BITFINEX_SECRET: ${EXCHANGE_BITFINEX_SECRET}
      EXCHANGE_BYBIT_API: ${EXCHANGE_BYBIT_API}
      EXCHANGE_BYBIT_SECRET: ${EXCHANGE_BYBIT_SECRET}
    depends_on:
      - db
      - redis
  db:
    image: postgres
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  redis:
    image: redis:latest
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./redis_data:/data
