services:
  mm-backend:
    build:
      context: ./packages/mm-backend
      dockerfile: Dockerfile
    container_name: mm-backend
    working_dir: /usr/src/app/packages/mm-backend
    command: ["pnpm", "start"]
    ports:
      - '${MM_BE_PORT}:${MM_BE_PORT}'
    environment:
      CORS_ORIGIN: ${CORS_ORIGIN}
      MM_BE_PORT: ${MM_BE_PORT}
      DATABASE_PORT: ${DATABASE_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      DATABASE_LOGGING_LEVEL: ${DATABASE_LOGGING_LEVEL}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE}
      DATABASE_AUTO_RUN_MIGRATIONS: ${DATABASE_AUTO_RUN_MIGRATIONS}
      DATABASE_SSL: ${DATABASE_SSL}
      REDIS_URL: ${REDIS_URL}
      TRADING_STRATEGY_EXECUTION_API: ${TRADING_STRATEGY_EXECUTION_API}
      JWT_SECRET: ${JWT_SECRET}
      CRON_SECRET: ${CRON_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      MIXIN_APP_ID: ${MIXIN_APP_ID}
      MIXIN_SESSION_ID: ${MIXIN_SESSION_ID}
      MIXIN_SERVER_PUBLIC_KEY: ${MIXIN_SERVER_PUBLIC_KEY}
      MIXIN_SESSION_PRIVATE_KEY: ${MIXIN_SESSION_PRIVATE_KEY}
      MIXIN_SPEND_PRIVATE_KEY: ${MIXIN_SPEND_PRIVATE_KEY}
      MIXIN_OAUTH_SECRET: ${MIXIN_OAUTH_SECRET}
      MIXIN_OAUTH_SCOPE: ${MIXIN_OAUTH_SCOPE}

  tse-backend:
    build:
      context: ./packages/tse-backend
      dockerfile: Dockerfile
    container_name: tse-backend
    working_dir: /usr/src/app/packages/tse-backend
    command: ["pnpm", "start"]
    ports:
      - '${TSE_BE_PORT}:${TSE_BE_PORT}'
    environment:
      SANDBOX: ${SANDBOX}
      CORS_ORIGIN: ${CORS_ORIGIN}
      TSE_BE_PORT: ${TSE_BE_PORT}
      DATABASE_PORT: ${DATABASE_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      DATABASE_LOGGING_LEVEL: ${DATABASE_LOGGING_LEVEL}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE}
      DATABASE_AUTO_RUN_MIGRATIONS: ${DATABASE_AUTO_RUN_MIGRATIONS}
      DATABASE_SSL: ${DATABASE_SSL}
      REDIS_URL: ${REDIS_URL}
      WS_PORT: ${WS_PORT}
      WS_NAMESPACE: ${WS_NAMESPACE}
      WS_CORS_ORIGIN: ${WS_CORS_ORIGIN}
      CRON_EXPRESSION: ${CRON_EXPRESSION}
      CRON_SECRET: ${CRON_SECRET}
      EXCHANGE_BYBIT_API: ${EXCHANGE_BYBIT_API}
      EXCHANGE_BYBIT_SECRET: ${EXCHANGE_BYBIT_SECRET}
    depends_on:
      - db
      - redis
  db:
    image: postgres
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data
