version: '3.8'

services:
  mm-backend:
    build:
      context: ../../
      dockerfile: packages/tse-backend/Dockerfile
    ports:
      - '${TSE_BE_PORT}:${TSE_BE_PORT}'
    environment:
      CORS_ORIGIN: ${CORS_ORIGIN}
      TSE_BE_PORT: ${TSE_BE_PORT}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_LOGGING_LEVEL: ${DATABASE_LOGGING_LEVEL}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE}
      DATABASE_AUTO_RUN_MIGRATIONS: ${DATABASE_AUTO_RUN_MIGRATIONS}
