services:
  mm-backend:
    build:
      context: ../../
      dockerfile: packages/tse-backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      SANDBOX: ${SANDBOX}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_LOGGING_LEVEL: ${DATABASE_LOGGING_LEVEL}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE}
      DATABASE_AUTO_RUN_MIGRATIONS: ${DATABASE_AUTO_RUN_MIGRATIONS}
      DATABASE_SSL: ${DATABASE_SSL}
      REDIS_URL: ${REDIS_URL}