version: '3.8'

services:
  mm-backend:
    build:
      context: ../../
      dockerfile: packages/tse-backend/Dockerfile
    ports:
      - '${TSE_BE_PORT}:${TSE_BE_PORT}'
    environment:
      SANDBOX: ${SANDBOX}
      CORS_ORIGIN: ${CORS_ORIGIN}
      TSE_BE_PORT: ${TSE_BE_PORT}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_LOGGING_LEVEL: ${DATABASE_LOGGING_LEVEL}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE}
      DATABASE_AUTO_RUN_MIGRATIONS: ${DATABASE_AUTO_RUN_MIGRATIONS}
      DATABASE_SSL: ${DATABASE_SSL}
      REDIS_URL: ${REDIS_URL}
      WS_PORT: ${WS_PORT}
      WS_NAMESPACE: ${WS_NAMESPACE}
      WS_CORS_ORIGIN: ${WS_CORS_ORIGIN}
      CRON_EXPRESSION: ${CRON_EXPRESSION}
      CRON_SECRET: ${CRON_SECRET}
      EXCHANGE_BINANCE_API: ${EXCHANGE_BINANCE_API}
      EXCHANGE_BINANCE_SECRET: ${EXCHANGE_BINANCE_SECRET}
      EXCHANGE_GATE_API: ${EXCHANGE_GATE_API}
      EXCHANGE_GATE_SECRET: ${EXCHANGE_GATE_SECRET}
      EXCHANGE_BITFINEX_API: ${EXCHANGE_BITFINEX_API}
      EXCHANGE_BITFINEX_SECRET: ${EXCHANGE_BITFINEX_SECRET}
      EXCHANGE_BYBIT_API: ${EXCHANGE_BYBIT_API}
      EXCHANGE_BYBIT_SECRET: ${EXCHANGE_BYBIT_SECRET}
