services:
  mm-backend:
    build:
      context: ../../
      dockerfile: packages/mm-backend/Dockerfile
    ports:
      - ${MM_BE_PORT}:${MM_BE_PORT}
    environment:
      CORS_ORIGIN: ${CORS_ORIGIN}
      MM_BE_PORT: ${MM_BE_PORT}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_LOGGING_LEVEL: ${DATABASE_LOGGING_LEVEL}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE}
      DATABASE_AUTO_RUN_MIGRATIONS: ${DATABASE_AUTO_RUN_MIGRATIONS}
      DATABASE_SSL: ${DATABASE_SSL}
      REDIS_URL: ${REDIS_URL}
      TRADING_STRATEGY_EXECUTION_API: ${TRADING_STRATEGY_EXECUTION_API}
      JWT_SECRET: ${JWT_SECRET}
      CRON_SECRET: ${CRON_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      MIXIN_APP_ID: ${MIXIN_APP_ID}
      MIXIN_SESSION_ID: ${MIXIN_SESSION_ID}
      MIXIN_SERVER_PUBLIC_KEY: ${MIXIN_SERVER_PUBLIC_KEY}
      MIXIN_SESSION_PRIVATE_KEY: ${MIXIN_SESSION_PRIVATE_KEY}
      MIXIN_SPEND_PRIVATE_KEY: ${MIXIN_SPEND_PRIVATE_KEY}
      MIXIN_OAUTH_SECRET: ${MIXIN_OAUTH_SECRET}
      MIXIN_OAUTH_SCOPE: ${MIXIN_OAUTH_SCOPE}
