name: Mr Market App Check

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - 'packages/mm-backend/**'
  workflow_dispatch:

jobs:
  job-lint:
    name: Mr Market Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        working-directory: packages/mm-backend
        run: pnpm install
      - name: Run ESLint
        working-directory: packages/mm-backend
        run: pnpm lint
  job-app-test:
    name: Mr Market App Test
    runs-on: ubuntu-latest
    needs: job-lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        working-directory: packages/mm-backend
        run: pnpm install
      - name: Build the project
        working-directory: packages/mm-backend
        run: pnpm build
      - name: Run unit tests
        working-directory: packages/mm-backend
        run: pnpm test
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: end2end
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        working-directory: packages/mm-backend
        run: pnpm install
      - name: Copy ENV file
        run: echo "${{ vars.APP_ENV_FILE }}" > .env
      - name: Convert .env file to use LF (Unix) line endings
        run: |
          sed -i 's/\r$//' .env
      - name: Load environment variables from .env
        run: |
          set -a
          source .env
          set +a
      - name: Run e2e tests
        working-directory: packages/mm-backend
        run: pnpm test:e2e